stages:
  prepare:
    cmd: python src/prepare.py data/50_Startups.csv
    deps:
    - data/50_Startups.csv
    - src/prepare.py
    params:
    - prepare.seed
    - prepare.split
    outs:
    - data/prepared
  train:
    cmd: python src/train.py data/prepared
    deps:
    - data/prepared
    - src/train.py
    outs:
    - model.pkl
  train2:
    cmd: python src/train2.py data/prepared
    deps:
    - data/prepared
    - src/train2.py
    outs:
    - model2.pkl
  evaluate:
    cmd: python src/evaluate.py model.pkl evaluate
    deps:
    - model.pkl
    - data/prepared
    - src/evaluate.py
    metrics:
    - evaluate
  evaluate2:
    cmd: python src/evaluate.py model2.pkl evaluate2
    deps:
    - model2.pkl
    - data/prepared
    - src/evaluate.py
    metrics:
    - evaluate2
metrics:
- evaluate/metrics.json
- evaluate2/metrics.json
plots:
- evaluate/plots/metrics:
    x: step
- evaluate2/plots/metrics:
    x: step
